version: '3.8'

services:
  static_web_server:
    container_name: static_web_server
    build: ./static-web-server
    # restart: always
    #ports:
     # - "8080:80"
    volumes:
      - ./static-web-server/logs:/var/log/nginx
    labels:
      - traefik.http.routers.static-web-server.rule=Host(`localhost`)
      #- traefik.http.routers.static-web-server.service=www-service

  #api_server:
    #container_name: api_server
    #build: ./api-server
    # restart: always


  traefik:
    image: traefik
    command:
      - --api.insecure=true  # Enable Traefik dashboard
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80" # Web-server
      - "8080:8080" # Dashboard


