version: '3.8'

services:
  static_web_server:
    #container_name: static-web-server
    build: ./static-web-server
    expose:
      - "80"
    volumes:
      - ./static-web-server/logs:/var/log/nginx
      #- ./reverse-proxy/traefik.yml:/etc/traefik/traefik.yml:ro
    labels:
      - traefik.http.routers.static-web-server.rule=Host(`static.localhost`)
    deploy:
      replicas:
        5

  api_server:
    #container_name: api_server
    build: ./api-server
    expose:
     - "80"
    labels:
      - traefik.http.routers.api-server.rule=PathPrefix(`/api/`)
      - traefik.services.api-server.loadBalancer.sticky=true
      - traefik.services.api-server.loadBalancer.sticky.cookie.name=MyBeloved
      - traefik.services.api-server.loadBalancer.sticky.cookie.secure=true
    deploy:
      replicas:
        5

  traefik:
    image: traefik
    command:
      - --api.insecure=true  # Enable Traefik dashboard
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /reverse-proxy/traefik.yaml:/etc/traefik/traefik.yaml
    ports:
      - "80:80" # Web-server
      - "8080:8080" # Dashboard


