version: '3.8'

services:
  static-web-server:
    container_name: static-web-server
    build: ./static-web-server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./static-web-server/logs:/var/log/nginx