version: '3.8'

services:
  staticWebServer:
    container_name: staticWebServer
    build: ./static-web-server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./logs/nginx:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf