## Static configuration
api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file: # specify dynamic config file
    filename: "/etc/traefik/dynamic/selftls.yml"
    watch: true # allow traefik to watch for file change during its execution



